### ISSUE TITLE
Add white background to supporters

### ISSUE THREAD

**Issue by ayr-ton** [agile-alliance-brazil/agile-brazil-hotsite#106]
Like sponsors area.
(The fix for sponsors ares was manually removing the alpha properties from the images with Gimp)

**Comment by taandsoul** [comment]
@ayr-ton Precisa dos logos de sponsors com fundo transparente? Posso fazer isso? :)

**Comment by ayr-ton** [comment]
É o contrário. Na verdade corrigiram esse problema com um PR recentemente resolvendo isso no CSS. 
Vou subir umas outras issues relacionadas e te marcar. :-)
Obrigado pelo interesse.
