### ISSUE TITLE
Primeira página com informações de 2020

### ISSUE THREAD

**Issue by ayr-ton** [agile-alliance-brazil/agile-brazil-hotsite#121]
Usando o Gatsby (ver #108), precisamos ter uma página com:

- Uma figura que represente Porto Alegre
- O local do evento
- Data do evento
- Rodapé com redes sociais e contato

(Similar com a página de 2019, mas com conteúdo atualizado)

**Comment by ayr-ton** [comment]
Removi as coisas de template para a issue #136

**Comment by pccassin** [comment]
@ayr-ton acho que com os esforços da semana podemos fechar esta também, não?

**Comment by ayr-ton** [comment]
Sim \o/

**Comment by pccassin** [comment]
Fechando a issue, pois já temos a página. Só está faltando ir para prod.

**Comment by ayr-ton** [comment]
\o/
