### ISSUE TITLE
New template for 2020

### ISSUE THREAD

**Issue by ayr-ton** [agile-alliance-brazil/agile-brazil-hotsite#136]
Using Gatsby (see #108), we need a new template:

Something that looks like the 2019 or 2015 page.

Better CSS and diagramming. 
Better color harmony.

**Comment by ayr-ton** [comment]
https://www.figma.com/file/PYcZKipxSi6EhKQiGSyudk/Home?node-id=0%3A1

https://color.adobe.com/AB-2020-Shades-color-theme-13622874

https://color.adobe.com/AB-2020-Shades-color-theme-13622874

**Comment by ayr-ton** [comment]
![Desktop - 1 (1)](https://user-images.githubusercontent.com/1090517/67964180-986b6f80-fbde-11e9-8c3d-7cc1cd1fecac.jpg)
![Mobile (1)](https://user-images.githubusercontent.com/1090517/67964184-9acdc980-fbde-11e9-8ce6-14a126f1f374.jpg)

Work from Paulo Cassin

**Comment by daravahn** [comment]
@ayr-ton testei a build de staging com os ajustes que fiz pro placeholder e as imagens ficaram com algum problema, pode me ajudar?

**Comment by ayr-ton** [comment]
@daravahn Resolvido no #134 o/

**Comment by ayr-ton** [comment]
Acho que a gente pode fechar essa issue aqui também, né?
cc.: @daravahn @pccassin
