### ISSUE TITLE
Replace GatsbyJS favicon for one by Agile Brazil

### ISSUE THREAD

**Issue by ayr-ton** [agile-alliance-brazil/agile-brazil-hotsite#159]

**Comment by afucher** [comment]
Should we ask the organization to get a favicon?

**Comment by ayr-ton** [comment]
@afucher I believe there's already one in the legacy directory. Let me check...

**Comment by ayr-ton** [comment]
Here it is:
https://github.com/agile-alliance-brazil/agile-brazil-hotsite/blob/2020/website_legacy/static/img/favicon.png
and 
https://github.com/agile-alliance-brazil/agile-brazil-hotsite/blob/2020/website_legacy/static/img/favicon.ico

**Comment by ayr-ton** [comment]
Fixed in a931285bbb547e892fdc6b208261bad30620ff7d by @centeno
